[package]
name = "monkey_business"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad-tiled = "0.2.1"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
include_assets = "*"
better_term = "*"

[dependencies.macroquad]
version = "0.4.14"
features = ["audio", "default"]